### ISSUE TITLE
Problems getting this working on local k3d set-up

### ISSUE THREAD

**Issue by Analect** [WOGRA-AG/terraform-kustomization-os4ml#1] opened 2023-01-24 16:36 UTC
@WograTimKoehler, thanks for sharing these resources.
I was attempting to get things running locally.

It seems the guidance in the README might need some adjustment in order to be more generic. It would seem that a single-node cluster is not going to be sufficient to run this ... also, maybe your set-up with google is something specific to your org.

```
k3d cluster create os4ml-cluster --k3s-node-label 'cloud.google.com/gke-nodepool=highcpu-pool@server:0'
```
I tried with a basic 1-server, 3-agent k3d cluster.  I was getting these errors regarding a missing istio.

```
module.os4ml.kustomization_resource.argocd_p1["networking.istio.io/VirtualService/argocd/argocd-server"]: Still creating... [1m50s elapsed]
module.os4ml.kustomization_resource.argocd_p1["networking.istio.io/VirtualService/argocd/argocd-server"]: Still creating... [2m0s elapsed]
module.os4ml.kustomization_resource.argocd_p1["networking.istio.io/VirtualService/argocd/argocd-server"]: Still creating... [2m10s elapsed]
module.os4ml.kustomization_resource.argocd_p1["networking.istio.io/VirtualService/argocd/argocd-server"]: Still creating... [2m20s elapsed]
module.os4ml.kustomization_resource.argocd_p1["networking.istio.io/VirtualService/argocd/argocd-server"]: Still creating... [2m30s elapsed]
╷
│ Error: github.com/kbst/terraform-provider-kustomize/kustomize.kustomizationResourceCreate: "networking.istio.io/VirtualService/argocd/argocd-server": timed out waiting for: "networking.istio.io/v1beta1, Kind=VirtualService": couldn't find resource (21 retries)
│
│   with module.os4ml.kustomization_resource.argocd_p1["networking.istio.io/VirtualService/argocd/argocd-server"],
│   on .terraform/modules/os4ml/argocd.tf line 15, in resource "kustomization_resource" "argocd_p1":
│   15: resource "kustomization_resource" "argocd_p1" {
```
So instead, I ran with this cluster config.  I just kept in your `gke-nodepool` label, eventhough it's not going to be doing anything in my context. I just included the other config for now, as I was following [this](https://brettmostert.medium.com/k3d-kubernetes-istio-service-mesh-286a7ba3a64f) approach to installing `istio`, which is why I'm disabling the default `traefik`.

```
k3d cluster create os4ml-cluster -s 1 -a 4 --port 9080:80@loadbalancer --port 9443:443@loadbalancer --api-port 6443 --k3s-arg '--no-deploy=traefik@server:0' --k3s-node-label 'cloud.google.com/gke-nodepool=highcpu-pool@server:0'
```

Istio appears to install fine with `istioctl install --set profile=default`

I run:

```
terraform init
terraform apply --auto-approve
```
That appears to run ok with:

```
module.os4ml.kustomization_resource.argocd_p1["rbac.authorization.k8s.io/RoleBinding/argocd/argocd-applicationset-controller"]: Creation complete after 0s [id=c7adc3f9-eb7c-4d43-bca0-a21b13c8ac5c]
module.os4ml.kustomization_resource.argocd_p1["networking.k8s.io/NetworkPolicy/argocd/argocd-repo-server-network-policy"]: Creation complete after 0s [id=8218da19-27c6-430c-9cef-10f5f8d53f72]
module.os4ml.kustomization_resource.argocd_p1["rbac.authorization.k8s.io/RoleBinding/argocd/argocd-redis"]: Creation complete after 0s [id=fcf66478-d162-4a70-b74c-f4e8d42aedec]
module.os4ml.kustomization_resource.argocd_p1["argoproj.io/Application/argocd/cluster-config"]: Creation complete after 2s [id=4a2ecb65-e662-4eea-ad2e-69b6bc571533]
2023-01-24T16:14:49.438Z [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2023-01-24T16:14:49.438Z [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/kbst/kustomization/0.9.1/linux_amd64/terraform-provider-kustomization_v0.9.1 pid=7804
2023-01-24T16:14:49.438Z [DEBUG] provider: plugin exited

Apply complete! Resources: 58 added, 0 changed, 0 destroyed.
```
Pods for ArgoCD appear to come up fine ... but then the cluster suddenly hits a problem with all pods (istio, argocd, postgres) in an `Evicted` status. There seems to be a sudden surge in pods created to 91.

![image](https://user-images.githubusercontent.com/4063815/214348586-723f39ac-9384-4d13-b3b8-1d568ff695c5.png)

Would you have any suggestions on how I might troubleshoot this? What k3d cluster specs are you working with in terms of CPU/Memory? Thanks.

**Comment by pd-t** [comment] 2023-01-26 11:11
Hi @Analect! Thanks for this super detailed issue. I will have a closer look on this and try to reproduce it. I'll give you feedback, stay tuned!

**Comment by pd-t** [comment] 2023-01-26 11:32
@Analect Yeah, there is definitely a problem... @WograTimKoehler already had a short look on the code and has an idea how to fix the problem.  He is hopeful to push a fix till tomorrow!

**Comment by WograTimKoehler** [comment] 2023-01-26 22:59
Hi @Analect 
Thank you for sharing your issue and sorry for the struggle. We haven't been able to update this repo recently, because the project is evolving pretty fast from the current PoC.  

Your issue with the missing `istio` resources was caused by a race condition and should be fixed now. 
At present, the `terraform apply` command should only deploy the `argocd` server with all necessary configuration resources. Everything else, like `istio`, `minio`, `kubeflow` and stuff should be managed by `argocd` and automatically deployed by it. You can always just check what's going on, in the `argocd` frontend, if you forward it like this

```bash
kubectl port-forward -n argocd services/argocd-server 8000:443
```

The topic with the gke-label is a known issue and we will update the affected `NodeSelector`s in the near future.  
  
For a smoother and less error-prone startup, i added a file named `k3d-default.yaml` with the k3d-configuration i use for local development and testing. You can use it like this 
```bash
k3d cluster create --config ./k3d-default.yaml
```

I also updated the `readme` to reflect all these recent changes.  

I am not entirely sure what causes your last phenomenon with the `evicted` pods, but to me it looks like the `istio-operator` deployed by `argoCD` and the `istio` setup deployed by `istioctl install --set profile=default` weren't really happy with each other and simultaneously tried to kill the `pods` of each other and restart its own `pods` in a loop.  

Regarding the cluster specs, CPU shouldn't really be an issue. In the worst case, the training of a new model will take a while.  
Talking about RAM, i guess you should be fine with 6 - 8 GB of free ram, but we didn't really measure it recently, so i can't be sure and the deployment is a little blown right now. We will address this in one of the upcoming versions, so the RAM requirements should shrink a bit during the next weeks.  

I really hope this helps. If there are any further issues, please let us know

**Comment by Analect** [comment] 2023-02-02 22:07
@pd-t @WograTimKoehler .. thank you both for the updated instructions.

With some trial-and-error, I managed to get things working. 

I was still having trouble with Istio running on a default k3d cluster, so I amended your config file to remove `traefik` on deployment.

```
k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:0
```
I then pre-installed istio, as before with: `istioctl install --set profile=default`
Without this pre-installation, I kept hitting problems with argocd failing to roll-out all components in the cluster.

The other pre-requisite I found necessary was to have at least 22GB of free space on whatever VM you are running this on locally. Maybe 25GB is better.  That was how much disk was consumed by the time all 48 pods in the cluster came up.

I found accessing the ArgoCD front-end problematic with the `svc/argocd-server ` port-forward. Although I was applying the correct password, I kept getting `401 Unauthorized` logging in as admin.  Accessing it via the telepresence approach worked though.

On your Step 3 (you have two Step 2s in your README!) ... I was initially having trouble with Telepresence involving this [error](https://www.getambassador.io/docs/telepresence/latest/troubleshooting#too-many-files-open-error-when-running-telepresence-connect-on-linux), which I was able to fix with `sudo sysctl fs.inotify.max_user_instances=256`. It had previously been set to 128 on my system.

Now I need to explore the system some more. I notice in your [os4ml installation docs](https://wogra-ag.github.io/os4ml-docs/installation/) you mention `REMARK: We recommend to use the k3s:v1.21.7-k3s1 image in order to avoid API conflicts.` ... given that it's working for me on `rancher/k3s:v1.25.6-k3s1`, maybe that's no longer applicable.

By the way, are there more detailed docs than what is available [here](https://wogra-ag.github.io/os4ml-docs/)? 
Also, is the intention to somehow couple this with [shepard](https://gitlab.com/dlr-shepard)? ... I see reference to that elsewhere in your repos.

Thanks again.

**Comment by Analect** [comment] 2023-02-05 15:13
Just an update on this. Frustratingly only ever managed to get this running once. Eventhough I delete and recreate a new k3d cluster, the `terraform apply --auto-approve` keeps getting stuck here:

```
Error: github.com/kbst/terraform-provider-kustomize/kustomize.kustomizationResourceExists: "argoproj.io/Application/argocd/cluster-config": timed out waiting for: "argoproj.io/v1alpha1, Kind=Application": couldn't find resource (21 retries)
│
│   with kustomization_resource.argocd_p1["argoproj.io/Application/argocd/cluster-config"],
│   on argocd.tf line 15, in resource "kustomization_resource" "argocd_p1":
│   15: resource "kustomization_resource" "argocd_p1" {
```
The pre-install of Istio (which I thought previously resolved my problems), looks like this:
```
istioctl install --set profile=default -y
✔ Istio core installed
✔ Istiod installed
✔ Ingress gateways installed
✔ Installation complete
Making this installation the default for injection and validation.

Thank you for installing Istio 1.16.  Please take a few minutes to tell us about your install/upgrade experience!  https://forms.gle/99uiMML96AmsXY5d6
```

**Closed as completed** 2023-02-13 16:03 UTC
